import app from './app-v071';
import type { Env } from './types';

const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8'}});
const esc=(s:unknown)=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
async function sha256(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('');}
function cookies(req:Request){const out:Record<string,string>={};for(const p of (req.headers.get('cookie')||'').split(';')){const [k,...r]=p.trim().split('=');if(k)out[k]=decodeURIComponent(r.join('='));}return out;}
async function isAdmin(req:Request,env:Env){if(!env.ADMIN_TOKEN)return true;const b=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'');return b===env.ADMIN_TOKEN||cookies(req).class_admin===await sha256(env.ADMIN_TOKEN);}
async function requireAdmin(req:Request,env:Env){if(await isAdmin(req,env))return null;return new Response(null,{status:302,headers:{location:'/admin/login'}});}
function page(title:string,body:string,script=''){return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>*{box-sizing:border-box}body{margin:0;background:#f6f7f9;color:#1f2937;font-family:system-ui,-apple-system,"Noto Sans TC",sans-serif}.wrap{max-width:760px;margin:20px auto;padding:12px}.card{background:#fff;border-radius:18px;padding:20px;margin-bottom:14px;box-shadow:0 8px 28px rgba(0,0,0,.06)}.btn{display:inline-block;border:0;border-radius:12px;padding:11px 15px;font-weight:800;text-decoration:none;cursor:pointer}.primary{background:#111827;color:#fff}.secondary{background:#eef2f7;color:#111827}.ok{background:#ecfdf5;color:#166534;padding:12px;border-radius:12px}.warn{background:#fff7ed;color:#9a3412;padding:12px;border-radius:12px}.field input{width:100%;padding:12px;border:1px solid #d1d5db;border-radius:12px;font-size:17px}video{width:100%;border-radius:16px;background:#111;max-height:460px}.row{display:flex;gap:10px;align-items:center}.muted{color:#6b7280}@media(max-width:640px){.row{display:grid}}</style></head><body>${body}<script>${script}</script></body></html>`;}
async function scannerPage(){return new Response(page('掃碼報到',`<div class="wrap"><div class="card"><div class="row"><a class="btn secondary" href="/admin">後台</a><h1>QR 掃碼報到</h1></div><p class="muted">掃描電子票券 QR；若瀏覽器不支援相機 QR 偵測，可直接輸入報名編號。</p></div><div class="card"><video id="video" playsinline></video><p><button id="start" class="btn primary">開啟相機掃描</button></p><div class="field"><input id="code" placeholder="REG-260818-XXXXXX"></div><p><button id="submit" class="btn primary">確認報到</button></p><div id="result"></div></div></div>`,`let stream=null,detector=null,busy=false;const out=document.getElementById('result'),inp=document.getElementById('code'),video=document.getElementById('video');async function checkin(code){if(!code||busy)return;busy=true;const r=await fetch('/api/v1/admin/checkin/'+encodeURIComponent(code),{method:'POST'});const d=await r.json();out.innerHTML=d.success?'<div class="ok"><b>'+d.registration.contact_name+'</b><br>'+d.registration.event_title+'｜'+d.registration.total_quantity+' 人｜'+(d.alreadyCheckedIn?'已報到過':'報到成功')+'</div>':'<div class="warn">'+(d.error||'報到失敗')+'</div>';busy=false;if(d.success)inp.value='';}document.getElementById('submit').onclick=()=>checkin(inp.value.trim());document.getElementById('start').onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});video.srcObject=stream;await video.play();if('BarcodeDetector'in window){detector=new BarcodeDetector({formats:['qr_code']});scan();}else out.innerHTML='<div class="warn">此瀏覽器不支援自動 QR 偵測，請輸入報名編號。</div>';}catch(e){out.innerHTML='<div class="warn">無法開啟相機：'+e.message+'</div>';}};async function scan(){if(!detector||!stream)return;try{const codes=await detector.detect(video);if(codes.length){const v=codes[0].rawValue||'';inp.value=v;await checkin(v);await new Promise(r=>setTimeout(r,1200));}}catch{}requestAnimationFrame(scan);}`),{headers:{'content-type':'text/html; charset=utf-8'}});}
function csvCell(v:unknown){const s=String(v??'');return `"${s.replace(/"/g,'""')}"`;}
async function exportCsv(env:Env,eventId:string){const event=await env.CLASS_DB.prepare('SELECT title FROM events WHERE id=?').bind(eventId).first<Record<string,any>>();if(!event)return json({success:false,error:'活動不存在'},404);const rows=await env.CLASS_DB.prepare(`SELECT r.registration_no,r.contact_name,r.contact_phone,r.contact_email,r.total_quantity,r.total_amount,r.registration_status,r.payment_status,r.created_at,s.name session_name,(SELECT GROUP_CONCAT(ri.item_name_snapshot||' x '||ri.quantity,' / ') FROM registration_items ri WHERE ri.registration_id=r.id) items FROM registrations r LEFT JOIN event_sessions s ON s.id=r.session_id WHERE r.event_id=? ORDER BY r.created_at DESC`).bind(eventId).all<Record<string,any>>();const head=['報名編號','聯絡人','手機','Email','梯次','項目','人數','金額','報名狀態','付款狀態','建立時間'];const lines=[head,...rows.results.map(r=>[r.registration_no,r.contact_name,r.contact_phone,r.contact_email,r.session_name,r.items,r.total_quantity,r.total_amount,r.registration_status,r.payment_status,r.created_at])].map(row=>row.map(csvCell).join(','));const csv='\uFEFF'+lines.join('\r\n');return new Response(csv,{headers:{'content-type':'text/csv; charset=utf-8','content-disposition':`attachment; filename="event-${eventId}.csv"`}});}
async function decorateRegistration(response:Response,token:string){if(!response.headers.get('content-type')?.includes('text/html'))return response;let text=await response.text();const button=`<div style="max-width:860px;margin:10px auto;padding:0 10px"><a href="/ticket/${encodeURIComponent(token)}" style="display:block;text-align:center;background:#111827;color:#fff;padding:12px;border-radius:12px;text-decoration:none;font-weight:800">顯示電子票券 / QR Code</a></div>`;text=text.replace('<body>','<body>'+button);return new Response(text,{status:response.status,headers:{'content-type':'text/html; charset=utf-8'}});}

export default{async fetch(request:Request,env:Env):Promise<Response>{const path=new URL(request.url).pathname.replace(/\/+$/,'')||'/';try{
  if(request.method==='GET'&&path==='/admin/checkin'){const denied=await requireAdmin(request,env);if(denied)return denied;return scannerPage();}
  const csv=path.match(/^\/api\/v1\/admin\/events\/([^/]+)\/export\.csv$/);if(request.method==='GET'&&csv){if(!await isAdmin(request,env))return json({success:false,error:'ADMIN_AUTH_REQUIRED'},401);return exportCsv(env,csv[1]);}
  const reg=path.match(/^\/registration\/([^/]+)$/);if(request.method==='GET'&&reg)return decorateRegistration(await app.fetch(request,env),reg[1]);
  return app.fetch(request,env);
}catch(e){return json({success:false,error:e instanceof Error?e.message:'系統錯誤'},400);}}};
