import app from './app-v09';
import type { Env } from './types';

const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8'}});
const esc=(s:unknown)=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
async function sha256(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('');}
function cookies(req:Request){const out:Record<string,string>={};for(const p of (req.headers.get('cookie')||'').split(';')){const [k,...r]=p.trim().split('=');if(k)out[k]=decodeURIComponent(r.join('='));}return out;}
async function isAdmin(req:Request,env:Env){if(!env.ADMIN_TOKEN)return true;const b=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'');return b===env.ADMIN_TOKEN||cookies(req).class_admin===await sha256(env.ADMIN_TOKEN);}
function page(title:string,body:string,script=''){return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>*{box-sizing:border-box}body{margin:0;background:#f6f7f9;color:#1f2937;font-family:system-ui,-apple-system,"Noto Sans TC",sans-serif}.wrap{max-width:980px;margin:20px auto;padding:12px}.card{background:#fff;border-radius:18px;padding:20px;margin-bottom:14px;box-shadow:0 8px 28px rgba(0,0,0,.06)}h1,h2,h3{margin-top:0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.field label{display:block;font-weight:800;margin-bottom:6px}.field input,.field select,.field textarea{width:100%;padding:11px;border:1px solid #d1d5db;border-radius:11px;font-size:16px}.btn{display:inline-block;border:0;border-radius:11px;padding:10px 14px;font-weight:800;cursor:pointer;text-decoration:none}.primary{background:#111827;color:#fff}.secondary{background:#eef2f7;color:#111827}.success{background:#166534;color:#fff}.danger{background:#dc2626;color:#fff}.warn{background:#fff7ed;color:#9a3412;padding:10px 12px;border-radius:12px}.ok{background:#ecfdf5;color:#166534;padding:10px 12px;border-radius:12px}.row{display:flex;gap:10px;align-items:center}.between{justify-content:space-between}.muted{color:#6b7280}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:10px;border-bottom:1px solid #e5e7eb;text-align:left;vertical-align:top}@media(max-width:680px){.row.mobile{display:grid}.table{display:block;overflow:auto}.wrap{padding:8px}}</style></head><body>${body}<script>${script}</script></body></html>`;}

async function policyPage(env:Env,eventId:string){const e=await env.CLASS_DB.prepare(`SELECT id,title,cancel_policy,cancel_deadline_hours,paid_cancel_action,payment_due_days FROM events WHERE id=?`).bind(eventId).first<Record<string,any>>();if(!e)return new Response(page('取消/付款規則','<div class="wrap"><div class="card warn">活動不存在</div></div>'),{status:404,headers:{'content-type':'text/html; charset=utf-8'}});return new Response(page(`${e.title}｜取消與付款規則`,`<div class="wrap"><div class="row mobile" style="margin-bottom:12px"><a class="btn secondary" href="/admin/event/${encodeURIComponent(eventId)}">活動儀表板</a><a class="btn secondary" href="/admin/refunds">退費管理</a></div><div class="card"><h1>${esc(e.title)}</h1><p class="muted">設定取消期限、已付款取消策略與後付付款期限。</p></div><div class="card"><h2>取消規則</h2><div class="grid"><div class="field"><label>是否允許自行取消</label><select id="cancelPolicy"><option value="allowed" ${e.cancel_policy!=='disabled'?'selected':''}>允許</option><option value="disabled" ${e.cancel_policy==='disabled'?'selected':''}>不允許</option></select></div><div class="field"><label>活動前幾小時截止取消</label><input id="cancelHours" type="number" min="0" placeholder="空白=不限" value="${e.cancel_deadline_hours??''}"></div><div class="field"><label>已付款取消</label><select id="paidAction"><option value="manual_refund" ${e.paid_cancel_action==='manual_refund'?'selected':''}>建立人工退費申請</option><option value="no_refund" ${e.paid_cancel_action==='no_refund'?'selected':''}>允許取消但不退費</option><option value="block" ${e.paid_cancel_action==='block'?'selected':''}>禁止自行取消</option></select></div><div class="field"><label>後付付款期限（天）</label><input id="dueDays" type="number" min="0" placeholder="空白=不設期限" value="${e.payment_due_days??''}"></div></div><p><button id="save" class="btn primary">儲存規則</button></p><div id="result"></div></div></div>`,`const EVENT_ID=${JSON.stringify(eventId)};document.getElementById('save').onclick=async()=>{const body={cancelPolicy:document.getElementById('cancelPolicy').value,cancelDeadlineHours:document.getElementById('cancelHours').value===''?null:Number(document.getElementById('cancelHours').value),paidCancelAction:document.getElementById('paidAction').value,paymentDueDays:document.getElementById('dueDays').value===''?null:Number(document.getElementById('dueDays').value)};const r=await fetch('/api/v1/admin/events/'+encodeURIComponent(EVENT_ID)+'/policy',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json();document.getElementById('result').innerHTML=d.success?'<div class="ok">已儲存</div>':'<div class="warn">'+(d.error||'儲存失敗')+'</div>';};`),{headers:{'content-type':'text/html; charset=utf-8'}});}

async function listRefunds(env:Env){const r=await env.CLASS_DB.prepare(`SELECT rr.id,rr.registration_id,rr.order_id,rr.amount,rr.status,rr.reason,rr.created_at,rr.processed_at,r.registration_no,r.contact_name,r.contact_phone,e.title event_title FROM refund_requests rr JOIN registrations r ON r.id=rr.registration_id JOIN events e ON e.id=r.event_id ORDER BY CASE rr.status WHEN 'pending' THEN 0 ELSE 1 END, rr.created_at DESC LIMIT 500`).all<Record<string,any>>();return r.results;}

async function refundPage(env:Env){const rows=await listRefunds(env);const body=rows.length?rows.map(x=>`<tr><td>${esc(x.registration_no)}<br><span class="muted">${esc(x.event_title)}</span></td><td>${esc(x.contact_name)}<br><span class="muted">${esc(x.contact_phone||'')}</span></td><td>$${Number(x.amount||0).toLocaleString('zh-TW')}</td><td>${esc(x.reason||'')}</td><td><b>${esc(x.status)}</b><br><span class="muted">${esc(x.created_at||'')}</span></td><td>${x.status==='pending'?`<div class="row mobile"><button class="btn success" data-act="approve" data-id="${esc(x.id)}">標記已退費</button><button class="btn danger" data-act="reject" data-id="${esc(x.id)}">駁回</button></div>`:''}</td></tr>`).join(''):'<tr><td colspan="6" class="muted">目前沒有退費申請</td></tr>';return new Response(page('退費管理',`<div class="wrap"><div class="row mobile" style="margin-bottom:12px"><a class="btn secondary" href="/admin">活動管理</a><h1>退費管理</h1></div><div class="card"><table class="table"><thead><tr><th>報名</th><th>聯絡人</th><th>金額</th><th>原因</th><th>狀態</th><th>處理</th></tr></thead><tbody>${body}</tbody></table><div id="result" style="margin-top:12px"></div></div></div>`,`document.querySelectorAll('[data-act]').forEach(b=>b.onclick=async()=>{const id=b.dataset.id,act=b.dataset.act;const note=prompt(act==='approve'?'退費備註（可空白）':'駁回原因（可空白）')||'';const r=await fetch('/api/v1/admin/refunds/'+encodeURIComponent(id)+'/'+act,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({note})});const d=await r.json();if(!d.success){document.getElementById('result').innerHTML='<div class="warn">'+(d.error||'處理失敗')+'</div>';return}location.reload();});`),{headers:{'content-type':'text/html; charset=utf-8'}});}

async function processRefund(env:Env,id:string,action:string,body:any){const r=await env.CLASS_DB.prepare(`SELECT rr.*,r.payment_status,o.id order_id FROM refund_requests rr JOIN registrations r ON r.id=rr.registration_id LEFT JOIN orders o ON o.id=rr.order_id WHERE rr.id=?`).bind(id).first<Record<string,any>>();if(!r)throw new Error('找不到退費申請');if(r.status!=='pending')throw new Error('此退費申請已處理');if(action==='approve'){await env.CLASS_DB.batch([env.CLASS_DB.prepare(`UPDATE refund_requests SET status='refunded',processed_at=CURRENT_TIMESTAMP,processed_note=? WHERE id=?`).bind(String(body?.note||''),id),env.CLASS_DB.prepare(`UPDATE registrations SET payment_status='refunded',updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(r.registration_id),...(r.order_id?[env.CLASS_DB.prepare(`UPDATE orders SET payment_status='refunded',updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(r.order_id)]:[])]);return{success:true,status:'refunded'};}if(action==='reject'){await env.CLASS_DB.prepare(`UPDATE refund_requests SET status='rejected',processed_at=CURRENT_TIMESTAMP,processed_note=? WHERE id=?`).bind(String(body?.note||''),id).run();return{success:true,status:'rejected'};}throw new Error('不支援的動作');}

async function reminderPage(env:Env){const r=await env.CLASS_DB.prepare(`SELECT r.id,r.registration_no,r.contact_name,r.contact_phone,r.contact_email,r.total_amount,r.payment_due_at,e.title event_title FROM registrations r JOIN events e ON e.id=r.event_id WHERE r.registration_status='confirmed' AND r.payment_status IN ('unpaid','pending') AND r.payment_due_at IS NOT NULL AND r.reminder_sent_at IS NULL AND datetime(r.payment_due_at)<=datetime('now','+24 hours') ORDER BY r.payment_due_at ASC LIMIT 500`).all<Record<string,any>>();const rows=r.results.map(x=>`<tr><td>${esc(x.registration_no)}<br>${esc(x.event_title)}</td><td>${esc(x.contact_name)}<br>${esc(x.contact_phone||'')}<br>${esc(x.contact_email||'')}</td><td>$${Number(x.total_amount||0).toLocaleString('zh-TW')}</td><td>${esc(x.payment_due_at)}</td><td><button class="btn primary" data-id="${esc(x.id)}">標記已提醒</button></td></tr>`).join('')||'<tr><td colspan="5" class="muted">目前沒有 24 小時內到期且未提醒的報名</td></tr>';return new Response(page('未付款提醒',`<div class="wrap"><div class="row mobile" style="margin-bottom:12px"><a class="btn secondary" href="/admin">活動管理</a><h1>未付款提醒</h1></div><div class="card"><p class="muted">這一頁先做提醒作業台；之後 LINE / Email / SMS adapter 可直接串同一批資料。</p><table class="table"><thead><tr><th>報名</th><th>聯絡方式</th><th>金額</th><th>付款期限</th><th>處理</th></tr></thead><tbody>${rows}</tbody></table></div></div>`,`document.querySelectorAll('[data-id]').forEach(b=>b.onclick=async()=>{const r=await fetch('/api/v1/admin/registrations/'+encodeURIComponent(b.dataset.id)+'/reminder-sent',{method:'POST'});const d=await r.json();if(d.success)location.reload();else alert(d.error||'失敗');});`),{headers:{'content-type':'text/html; charset=utf-8'}});}

export default{async fetch(request:Request,env:Env):Promise<Response>{const path=new URL(request.url).pathname.replace(/\/+$/,'')||'/';try{
  if(path.startsWith('/admin')||path.startsWith('/api/v1/admin')){if(!await isAdmin(request,env)){if(path.startsWith('/api/'))return json({success:false,error:'ADMIN_AUTH_REQUIRED'},401);return new Response(null,{status:302,headers:{location:'/admin/login'}});}}
  const policy=path.match(/^\/admin\/event\/([^/]+)\/policy$/);if(request.method==='GET'&&policy)return policyPage(env,policy[1]);
  if(request.method==='GET'&&path==='/admin/refunds')return refundPage(env);
  if(request.method==='GET'&&path==='/admin/reminders')return reminderPage(env);
  const refund=path.match(/^\/api\/v1\/admin\/refunds\/([^/]+)\/(approve|reject)$/);if(request.method==='POST'&&refund)return json(await processRefund(env,refund[1],refund[2],await request.json().catch(()=>({}))));
  if(request.method==='GET'&&path==='/api/v1/admin/refunds')return json({success:true,refunds:await listRefunds(env)});
  if(request.method==='GET'&&path==='/health')return json({success:true,service:env.APP_NAME,version:'0.10.0'});
  return app.fetch(request,env);
}catch(e){return json({success:false,error:e instanceof Error?e.message:'系統錯誤'},400);}}};
