import app from './app-v10';
import type { Env } from './types';

const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8'}});
const esc=(s:unknown)=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
async function sha256(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('');}
function cookies(req:Request){const out:Record<string,string>={};for(const p of (req.headers.get('cookie')||'').split(';')){const [k,...r]=p.trim().split('=');if(k)out[k]=decodeURIComponent(r.join('='));}return out;}
async function isAdmin(req:Request,env:Env){if(!env.ADMIN_TOKEN)return true;const b=req.headers.get('authorization')?.replace(/^Bearer\s+/i,'');return b===env.ADMIN_TOKEN||cookies(req).class_admin===await sha256(env.ADMIN_TOKEN);}
function page(title:string,body:string,script=''){return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>*{box-sizing:border-box}body{margin:0;background:#f6f7f9;color:#1f2937;font-family:system-ui,-apple-system,"Noto Sans TC",sans-serif}.wrap{max-width:980px;margin:20px auto;padding:12px}.card{background:#fff;border-radius:18px;padding:20px;margin-bottom:14px;box-shadow:0 8px 28px rgba(0,0,0,.06)}.btn{display:inline-block;border:0;border-radius:11px;padding:10px 14px;font-weight:800;cursor:pointer;text-decoration:none}.secondary{background:#eef2f7;color:#111827}.success{background:#166534;color:#fff}.danger{background:#dc2626;color:#fff}.warn{background:#fff7ed;color:#9a3412;padding:10px 12px;border-radius:12px}.row{display:flex;gap:8px;align-items:center}.muted{color:#6b7280}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:10px;border-bottom:1px solid #e5e7eb;text-align:left;vertical-align:top}textarea{width:100%;padding:9px;border:1px solid #d1d5db;border-radius:10px}@media(max-width:680px){.row{display:grid}.table{display:block;overflow:auto}.wrap{padding:8px}}</style></head><body>${body}<script>${script}</script></body></html>`;}

async function listRefunds(env:Env){const r=await env.CLASS_DB.prepare(`SELECT rr.id,rr.registration_id,rr.order_id,rr.amount,rr.status,rr.reason,rr.requested_at,rr.processed_at,rr.note,r.registration_no,r.contact_name,r.contact_phone,e.title event_title FROM refund_requests rr JOIN registrations r ON r.id=rr.registration_id JOIN events e ON e.id=r.event_id ORDER BY CASE rr.status WHEN 'pending' THEN 0 ELSE 1 END, rr.requested_at DESC LIMIT 500`).all<Record<string,any>>();return r.results;}

async function refundPage(env:Env){const rows=await listRefunds(env);const trs=rows.length?rows.map(x=>`<tr><td>${esc(x.registration_no)}<br><span class="muted">${esc(x.event_title)}</span></td><td>${esc(x.contact_name)}<br><span class="muted">${esc(x.contact_phone||'')}</span></td><td>$${Number(x.amount||0).toLocaleString('zh-TW')}</td><td>${esc(x.reason||'')}</td><td><b>${esc(x.status)}</b><br><span class="muted">${esc(x.requested_at||'')}</span></td><td>${x.status==='pending'?`<textarea id="note_${esc(x.id)}" rows="2" placeholder="處理備註（可空白）"></textarea><div class="row" style="margin-top:8px"><button class="btn success" data-act="approve" data-id="${esc(x.id)}">標記已退費</button><button class="btn danger" data-act="reject" data-id="${esc(x.id)}">駁回</button></div>`:`<span class="muted">${esc(x.note||'')}</span>`}</td></tr>`).join(''):'<tr><td colspan="6" class="muted">目前沒有退費申請</td></tr>';return new Response(page('退費管理',`<div class="wrap"><div class="row" style="margin-bottom:12px"><a class="btn secondary" href="/admin">活動管理</a><h1>退費管理</h1></div><div class="card"><table class="table"><thead><tr><th>報名</th><th>聯絡人</th><th>金額</th><th>原因</th><th>狀態</th><th>處理</th></tr></thead><tbody>${trs}</tbody></table><div id="msg"></div></div></div>`,`document.querySelectorAll('[data-act]').forEach(b=>b.onclick=async()=>{const id=b.dataset.id,act=b.dataset.act,note=document.getElementById('note_'+id)?.value||'';b.disabled=true;const r=await fetch('/api/v1/admin/refunds/'+encodeURIComponent(id)+'/'+act,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({note})});const d=await r.json();if(d.success){location.reload();return}document.getElementById('msg').innerHTML='<div class="warn">'+(d.error||'處理失敗')+'</div>';b.disabled=false;});`),{headers:{'content-type':'text/html; charset=utf-8'}});}

async function processRefund(env:Env,id:string,action:string,body:any){const r=await env.CLASS_DB.prepare(`SELECT rr.*,o.id order_id FROM refund_requests rr LEFT JOIN orders o ON o.id=rr.order_id WHERE rr.id=?`).bind(id).first<Record<string,any>>();if(!r)throw new Error('找不到退費申請');if(r.status!=='pending')throw new Error('此退費申請已處理');const note=String(body?.note||'');if(action==='approve'){const st:any[]=[env.CLASS_DB.prepare(`UPDATE refund_requests SET status='refunded',processed_at=CURRENT_TIMESTAMP,note=? WHERE id=?`).bind(note,id),env.CLASS_DB.prepare(`UPDATE registrations SET payment_status='refunded',updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(r.registration_id)];if(r.order_id)st.push(env.CLASS_DB.prepare(`UPDATE orders SET payment_status='refunded',updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(r.order_id));await env.CLASS_DB.batch(st);return{success:true,status:'refunded'};}if(action==='reject'){await env.CLASS_DB.prepare(`UPDATE refund_requests SET status='rejected',processed_at=CURRENT_TIMESTAMP,note=? WHERE id=?`).bind(note,id).run();return{success:true,status:'rejected'};}throw new Error('不支援的動作');}

export default{async fetch(request:Request,env:Env):Promise<Response>{const path=new URL(request.url).pathname.replace(/\/+$/,'')||'/';try{if((path.startsWith('/admin')||path.startsWith('/api/v1/admin'))&&!await isAdmin(request,env)){if(path.startsWith('/api/'))return json({success:false,error:'ADMIN_AUTH_REQUIRED'},401);return new Response(null,{status:302,headers:{location:'/admin/login'}});}if(request.method==='GET'&&path==='/admin/refunds')return refundPage(env);const r=path.match(/^\/api\/v1\/admin\/refunds\/([^/]+)\/(approve|reject)$/);if(request.method==='POST'&&r)return json(await processRefund(env,r[1],r[2],await request.json().catch(()=>({}))));if(request.method==='GET'&&path==='/api/v1/admin/refunds')return json({success:true,refunds:await listRefunds(env)});if(request.method==='GET'&&path==='/health')return json({success:true,service:env.APP_NAME,version:'0.10.1'});return app.fetch(request,env);}catch(e){return json({success:false,error:e instanceof Error?e.message:'系統錯誤'},400);}}};
