import app from './app-v06';
import type { Env } from './types';

const jsonHeaders = { 'content-type':'application/json; charset=utf-8' };
const json = (data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:jsonHeaders});
const html = (body:string,status=200,headers:HeadersInit={})=>new Response(body,{status,headers:{'content-type':'text/html; charset=utf-8',...headers}});
const uid=(p:string)=>`${p}_${crypto.randomUUID().replaceAll('-','')}`;
const rawToken=()=>crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');
const esc=(s:unknown)=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
async function sha256(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('');}
function cookies(req:Request){const out:Record<string,string>={};for(const p of (req.headers.get('cookie')||'').split(';')){const [k,...r]=p.trim().split('=');if(k)out[k]=decodeURIComponent(r.join('='));}return out;}
function shell(title:string,body:string,script=''){return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>*{box-sizing:border-box}body{margin:0;background:#f6f7f9;color:#1f2937;font-family:system-ui,-apple-system,"Noto Sans TC",sans-serif}.wrap{max-width:980px;margin:24px auto;padding:14px}.card{background:#fff;border-radius:18px;padding:20px;box-shadow:0 8px 28px rgba(0,0,0,.06);margin-bottom:14px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px}.row{display:flex;gap:10px;align-items:center}.between{justify-content:space-between}.field label{display:block;font-weight:800;margin-bottom:6px}.field input,.field select{width:100%;padding:11px;border:1px solid #d1d5db;border-radius:11px;font-size:16px}.btn{display:inline-block;border:0;border-radius:11px;padding:10px 14px;font-weight:800;cursor:pointer;text-decoration:none}.primary{background:#111827;color:#fff}.secondary{background:#eef2f7;color:#111827}.danger{background:#dc2626;color:#fff}.muted{color:#6b7280}.pill{display:inline-block;padding:4px 9px;border-radius:999px;background:#eef2ff;color:#3730a3;font-size:13px;font-weight:800}.ticket{max-width:520px;margin:24px auto;background:white;border-radius:24px;padding:26px;box-shadow:0 12px 40px rgba(0,0,0,.1);text-align:center}.qr{width:220px;height:220px;margin:18px auto}.code{font-size:24px;font-weight:900;letter-spacing:1px}@media(max-width:640px){.row.mobile{display:grid}.wrap{padding:8px}}</style></head><body>${body}<script>${script}</script></body></html>`;}
async function currentIdentity(req:Request,env:Env){const raw=req.headers.get('x-class-identity-token')||cookies(req).class_identity;if(!raw)return null;return env.CLASS_DB.prepare(`SELECT * FROM identity_sessions WHERE session_token_hash=? AND datetime(expires_at)>datetime('now') LIMIT 1`).bind(await sha256(raw)).first<Record<string,any>>();}
async function apiClient(req:Request,env:Env){const raw=req.headers.get('x-api-key')||req.headers.get('authorization')?.replace(/^Bearer\s+/i,'');if(!raw)return null;return env.CLASS_DB.prepare(`SELECT * FROM api_clients WHERE api_key_hash=? AND is_active=1 LIMIT 1`).bind(await sha256(raw)).first<Record<string,any>>();}
async function createHandoff(env:Env,client:Record<string,any>,body:any){if(!body?.identityToken)throw new Error('identityToken 必填');const session=await env.CLASS_DB.prepare(`SELECT * FROM identity_sessions WHERE session_token_hash=? AND tenant_key=? AND datetime(expires_at)>datetime('now') LIMIT 1`).bind(await sha256(body.identityToken),client.tenant_key).first<Record<string,any>>();if(!session)throw new Error('IDENTITY_TOKEN_INVALID');const code=`hnd_${rawToken()}`;const ret=String(body.returnPath||'/events');if(!ret.startsWith('/')||ret.startsWith('//'))throw new Error('returnPath 必須為站內路徑');const expires=new Date(Date.now()+Math.min(Math.max(Number(body.expiresSeconds||120),30),600)*1000).toISOString();await env.CLASS_DB.prepare(`INSERT INTO identity_handoffs(id,tenant_key,identity_session_id,handoff_code_hash,return_path,expires_at,created_by_client_id) VALUES(?,?,?,?,?,?,?)`).bind(uid('hnd'),client.tenant_key,session.id,await sha256(code),ret,expires,client.id).run();return{success:true,handoffCode:code,handoffUrl:`/auth/handoff?code=${encodeURIComponent(code)}`,expiresAt:expires};}
async function consumeHandoff(req:Request,env:Env){const code=new URL(req.url).searchParams.get('code');if(!code)throw new Error('缺少 handoff code');const h=await env.CLASS_DB.prepare(`SELECT h.*,s.session_token_hash,s.expires_at session_expires FROM identity_handoffs h JOIN identity_sessions s ON s.id=h.identity_session_id WHERE h.handoff_code_hash=? AND h.consumed_at IS NULL AND datetime(h.expires_at)>datetime('now') AND datetime(s.expires_at)>datetime('now') LIMIT 1`).bind(await sha256(code)).first<Record<string,any>>();if(!h)throw new Error('handoff 已失效或使用過');const newRaw=`ids_${rawToken()}`;await env.CLASS_DB.batch([env.CLASS_DB.prepare(`UPDATE identity_sessions SET session_token_hash=?,last_used_at=CURRENT_TIMESTAMP WHERE id=?`).bind(await sha256(newRaw),h.identity_session_id),env.CLASS_DB.prepare(`UPDATE identity_handoffs SET consumed_at=CURRENT_TIMESTAMP WHERE id=?`).bind(h.id)]);return new Response(null,{status:302,headers:{location:h.return_path,'set-cookie':`class_identity=${encodeURIComponent(newRaw)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000`}});}
async function myPage(req:Request,env:Env){const idn=await currentIdentity(req,env);if(!idn)return new Response(null,{status:302,headers:{location:'/login?return=%2Fmy'}});const rows=await env.CLASS_DB.prepare(`SELECT r.access_token,r.registration_no,r.total_quantity,r.total_amount,r.registration_status,r.payment_status,e.title event_title,e.starts_at,e.location_name FROM registrations r JOIN events e ON e.id=r.event_id WHERE r.tenant_key=? AND r.external_member_id=? ORDER BY r.created_at DESC`).bind(idn.tenant_key,idn.external_member_id).all<Record<string,any>>();const cards=rows.results.length?rows.results.map(x=>`<a class="card" style="display:block;text-decoration:none;color:inherit" href="/registration/${encodeURIComponent(x.access_token)}"><div class="row between mobile"><div><h3>${esc(x.event_title)}</h3><div class="muted">${esc(x.starts_at||'時間待定')}｜${esc(x.location_name||'')}</div><div>${esc(x.registration_no)}｜${x.total_quantity} 人</div></div><div><span class="pill">${esc(x.registration_status)}</span><p><b>$${Number(x.total_amount||0).toLocaleString('zh-TW')}</b></p></div></div></a>`).join(''):'<div class="card muted">目前沒有報名紀錄</div>';return html(shell('我的報名',`<div class="wrap"><div class="card"><div class="row between mobile"><div><h1>我的報名</h1><p class="muted">${esc(idn.display_name||idn.external_member_id)}｜${esc(idn.provider)}</p></div><a class="btn secondary" href="/events">找活動</a></div></div>${cards}</div>`));}
async function ticketPage(env:Env,accessToken:string){const r=await env.CLASS_DB.prepare(`SELECT r.registration_no,r.contact_name,r.total_quantity,r.total_amount,r.registration_status,r.payment_status,e.title event_title,e.starts_at,e.location_name FROM registrations r JOIN events e ON e.id=r.event_id WHERE r.access_token=? LIMIT 1`).bind(accessToken).first<Record<string,any>>();if(!r)return html(shell('電子票券','<div class="wrap"><div class="card">找不到票券</div></div>'),404);const allowed=['confirmed','checked_in'];const ok=allowed.includes(r.registration_status);const payload=r.registration_no;return html(shell('電子票券',`<div class="ticket"><span class="pill">${ok?'有效票券':'目前不可報到'}</span><h1>${esc(r.event_title)}</h1><p class="muted">${esc(r.starts_at||'')}<br>${esc(r.location_name||'')}</p><div id="qr" class="qr"></div><div class="code">${esc(r.registration_no)}</div><p>${esc(r.contact_name)}｜${r.total_quantity} 人</p><p>付款：${esc(r.payment_status)}｜狀態：${esc(r.registration_status)}</p><a class="btn secondary" href="/registration/${encodeURIComponent(accessToken)}">查看報名資料</a></div><script src="https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.min.js"></script>`,`if(window.QRCode)new QRCode(document.getElementById('qr'),{text:${JSON.stringify(payload)},width:220,height:220});`));}
async function adminClientsPage(env:Env){const rows=await env.CLASS_DB.prepare(`SELECT id,tenant_key,name,scopes_json,is_active,last_used_at,created_at FROM api_clients ORDER BY created_at DESC`).all<Record<string,any>>();return html(shell('API Clients',`<div class="wrap"><div class="card"><div class="row between mobile"><div><h1>API Client 管理</h1><p class="muted">每個外部專案一組 Key，綁定 tenant。</p></div><a class="btn secondary" href="/admin">返回後台</a></div></div><div class="card"><h2>建立 Client</h2><div class="grid"><div class="field"><label>名稱</label><input id="name" placeholder="TDEA"></div><div class="field"><label>Tenant Key</label><input id="tenant" value="default"></div></div><p><button id="create" class="btn primary">建立 API Key</button></p><div id="result"></div></div><div class="card"><h2>既有 Clients</h2>${rows.results.map(x=>`<div class="row between mobile" style="padding:10px 0;border-bottom:1px solid #eee"><div><b>${esc(x.name)}</b> <span class="pill">${esc(x.tenant_key)}</span><div class="muted">${esc(x.id)}｜${x.is_active?'啟用':'停用'}｜最後使用 ${esc(x.last_used_at||'尚未')}</div></div>${x.is_active?`<button class="btn danger" data-disable="${esc(x.id)}">停用</button>`:''}</div>`).join('')||'<div class="muted">尚無 Client</div>'}</div></div>`,`document.getElementById('create').onclick=async()=>{const r=await fetch('/api/v1/admin/api-clients',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:document.getElementById('name').value,tenantKey:document.getElementById('tenant').value})});const d=await r.json();document.getElementById('result').innerHTML=d.success?'<div style="background:#ecfdf5;padding:12px;border-radius:12px"><b>請立即保存 API Key：</b><br><code style="word-break:break-all">'+d.apiKey+'</code></div>':'<div>'+d.error+'</div>'};document.querySelectorAll('[data-disable]').forEach(b=>b.onclick=async()=>{await fetch('/api/v1/admin/api-clients/'+b.dataset.disable+'/disable',{method:'POST'});location.reload()});`));}
async function disableClient(env:Env,id:string){await env.CLASS_DB.prepare(`UPDATE api_clients SET is_active=0 WHERE id=?`).bind(id).run();return{success:true};}

export default{async fetch(request:Request,env:Env):Promise<Response>{const url=new URL(request.url),path=url.pathname.replace(/\/+$/,'')||'/';try{
  if(request.method==='GET'&&path==='/auth/handoff')return consumeHandoff(request,env);
  if(request.method==='GET'&&path==='/my')return myPage(request,env);
  const ticket=path.match(/^\/ticket\/([^/]+)$/);if(request.method==='GET'&&ticket)return ticketPage(env,ticket[1]);
  if(request.method==='GET'&&path==='/admin/api-clients')return adminClientsPage(env);
  const dis=path.match(/^\/api\/v1\/admin\/api-clients\/([^/]+)\/disable$/);if(request.method==='POST'&&dis)return json(await disableClient(env,dis[1]));
  if(request.method==='POST'&&path==='/api/v1/integration/identity/handoff'){const c=await apiClient(request,env);if(!c)return json({success:false,error:'INVALID_API_KEY'},401);return json(await createHandoff(env,c,await request.json()),201);}
  return app.fetch(request,env);
}catch(e){return json({success:false,error:e instanceof Error?e.message:'系統錯誤'},400);}}};
