import type { Env } from './types';

const esc = (s: unknown) => String(s ?? '').replace(/[&<>\"]/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;' }[c] || c));
const html = (body: string) => new Response(body, { headers: { 'content-type':'text/html; charset=utf-8' } });

function shell(title: string, body: string, script = '') {
  return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>
  *{box-sizing:border-box}body{margin:0;font-family:system-ui,-apple-system,"Noto Sans TC",sans-serif;background:#f6f7f9;color:#1f2937}.wrap{max-width:860px;margin:0 auto;padding:14px}.card{background:#fff;border-radius:18px;padding:20px;margin-bottom:14px;box-shadow:0 8px 28px rgba(0,0,0,.06)}.hero{padding:0;overflow:hidden}.hero img{width:100%;display:block;max-height:420px;object-fit:cover}.hero .inner{padding:20px}h1,h2,h3{margin:0 0 12px}.muted{color:#6b7280}.stack{display:grid;gap:12px}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}.row{display:flex;gap:10px;align-items:center}.between{justify-content:space-between}.field label{display:block;font-weight:800;margin-bottom:6px}.field input,.field select,.field textarea{width:100%;padding:12px;border:1px solid #d1d5db;border-radius:12px;font-size:16px;background:white}.btn{border:0;border-radius:12px;padding:12px 15px;font-size:16px;font-weight:800;cursor:pointer}.primary{background:#111827;color:#fff}.secondary{background:#eef2f7;color:#111827}.qty{display:flex;align-items:center;gap:8px}.qty button{width:38px;height:38px;border:0;border-radius:10px;font-size:20px}.qty input{width:56px;text-align:center;padding:8px;border:1px solid #d1d5db;border-radius:10px}.item{border:1px solid #e5e7eb;border-radius:14px;padding:14px}.price{font-size:19px;font-weight:900}.total{font-size:26px;font-weight:900}.notice{padding:12px;border-radius:12px;background:#fff7ed;color:#9a3412}.ok{padding:12px;border-radius:12px;background:#ecfdf5;color:#166534}.hidden{display:none}.attendee{border-left:4px solid #d1d5db;padding-left:12px}.nav{margin-bottom:12px}.nav a{text-decoration:none;color:#111827;background:#fff;padding:8px 11px;border-radius:10px;font-weight:700}@media(max-width:640px){.grid2{grid-template-columns:1fr}.row.mobile{display:grid}.wrap{padding:9px}.card{padding:15px;border-radius:14px}}
  </style></head><body>${body}<script>${script}</script></body></html>`;
}

export async function renderPublicEventV05(env: Env, eventId: string): Promise<Response> {
  const event = await env.CLASS_DB.prepare('SELECT * FROM events WHERE id=? AND status=\'published\'').bind(eventId).first<Record<string,any>>();
  if (!event) return html(shell('活動不存在','<div class="wrap"><div class="card notice">活動不存在或尚未開放報名。</div></div>'));
  return html(shell(event.title, `<div class="wrap"><div class="nav"><a href="/events">返回活動列表</a></div><div id="app"><div class="card">載入中...</div></div></div>`, `
  const EVENT_ID=${JSON.stringify(eventId)};let data=null;let quantities={};
  const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const money=n=>new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(Number(n||0));
  const fieldHtml=(f,prefix)=>{const id=prefix+'_'+f.field_key,opt=(()=>{try{return JSON.parse(f.options_json||'[]')}catch{return[]}})();const req=f.is_required?' required':'';if(f.field_type==='textarea')return '<div class="field"><label>'+esc(f.label)+(f.is_required?' *':'')+'</label><textarea data-custom="'+esc(f.field_key)+'" data-prefix="'+esc(prefix)+'" id="'+esc(id)+'"'+req+'></textarea></div>';if(f.field_type==='select')return '<div class="field"><label>'+esc(f.label)+(f.is_required?' *':'')+'</label><select data-custom="'+esc(f.field_key)+'" data-prefix="'+esc(prefix)+'" id="'+esc(id)+'"'+req+'><option value="">請選擇</option>'+opt.map(x=>'<option value="'+esc(x)+'">'+esc(x)+'</option>').join('')+'</select></div>';if(f.field_type==='radio')return '<div class="field"><label>'+esc(f.label)+(f.is_required?' *':'')+'</label>'+opt.map(x=>'<label style="display:inline-block;margin-right:12px"><input type="radio" name="'+esc(id)+'" data-custom="'+esc(f.field_key)+'" data-prefix="'+esc(prefix)+'" value="'+esc(x)+'"'+req+'> '+esc(x)+'</label>').join('')+'</div>';if(f.field_type==='checkbox')return '<div class="field"><label>'+esc(f.label)+(f.is_required?' *':'')+'</label>'+opt.map(x=>'<label style="display:inline-block;margin-right:12px"><input type="checkbox" data-custom="'+esc(f.field_key)+'" data-prefix="'+esc(prefix)+'" value="'+esc(x)+'"> '+esc(x)+'</label>').join('')+'</div>';const t=['number','tel','email','date'].includes(f.field_type)?f.field_type:'text';return '<div class="field"><label>'+esc(f.label)+(f.is_required?' *':'')+'</label><input type="'+t+'" data-custom="'+esc(f.field_key)+'" data-prefix="'+esc(prefix)+'" id="'+esc(id)+'"'+req+'></div>'};
  function collectCustom(prefix){const out={};const nodes=[...document.querySelectorAll('[data-prefix="'+CSS.escape(prefix)+'"][data-custom]')];const keys=[...new Set(nodes.map(n=>n.dataset.custom))];for(const key of keys){const xs=nodes.filter(n=>n.dataset.custom===key);if(xs[0]?.type==='checkbox')out[key]=xs.filter(n=>n.checked).map(n=>n.value);else if(xs[0]?.type==='radio')out[key]=xs.find(n=>n.checked)?.value||'';else out[key]=xs[0]?.value||'';}return out;}
  function selectedItems(){return data.items.map(x=>({itemId:x.id,quantity:Number(quantities[x.id]||0)})).filter(x=>x.quantity>0)}
  function recalc(){let c=0,a=0;for(const x of data.items){const q=Number(quantities[x.id]||0);c+=q;a+=q*Number(x.unit_price||0)}document.getElementById('count').textContent=c;document.getElementById('amount').textContent=money(a);renderAttendees();let hint='免費活動：送出後直接報名成功';if(a>0&&data.event.registration_success_mode==='register_then_pay')hint='先完成報名，再依活動付款方式付款';if(a>0&&data.event.registration_success_mode==='pay_then_confirm')hint='付款完成後才算正式報名成功；付款前暫時保留名額';document.getElementById('modeHint').textContent=hint;}
  function renderAttendees(){const box=document.getElementById('attendees');if(!box)return;const total=selectedItems().reduce((n,x)=>n+x.quantity,0);if(data.event.attendee_data_mode==='contact_only'||!total){box.innerHTML='';return}const attendeeFields=data.fields.filter(f=>f.scope==='attendee');let html='<div class="card"><h2>參加者資料</h2><div class="stack">';let global=0;for(const sel of selectedItems()){const item=data.items.find(x=>x.id===sel.itemId);for(let i=1;i<=sel.quantity;i++){global++;const prefix='att_'+global;html+='<div class="attendee"><h3>'+esc(item.name)+'｜第 '+i+' 位</h3><input type="hidden" data-att-item="'+esc(item.id)+'" data-att-index="'+i+'" data-att-prefix="'+prefix+'"><div class="grid2"><div class="field"><label>姓名 *</label><input data-att-name="'+prefix+'" required></div>'+(data.event.attendee_data_mode==='full'?'<div class="field"><label>手機</label><input data-att-phone="'+prefix+'" inputmode="tel"></div><div class="field"><label>Email</label><input data-att-email="'+prefix+'" type="email"></div>':'')+'</div>'+attendeeFields.map(f=>fieldHtml(f,prefix)).join('')+'</div>'}}html+='</div></div>';box.innerHTML=html;}
  function render(){const e=data.event;const contactFields=data.fields.filter(f=>f.scope==='contact');document.getElementById('app').innerHTML='<div class="card hero">'+(e.banner_url?'<img src="'+esc(e.banner_url)+'" alt="">':'')+'<div class="inner"><h1>'+esc(e.title)+'</h1><p class="muted">'+esc(e.starts_at||'')+(e.location_name?' · '+esc(e.location_name):'')+'</p><p>'+esc(e.description||'').replace(/\\n/g,'<br>')+'</p></div></div><form id="regForm">'+(data.sessions.length?'<div class="card"><h2>選擇梯次</h2><div class="field"><select id="session" required><option value="">請選擇梯次</option>'+data.sessions.map(s=>'<option value="'+esc(s.id)+'">'+esc(s.name)+(s.starts_at?'｜'+esc(s.starts_at):'')+'</option>').join('')+'</select></div></div>':'')+'<div class="card"><h2>報名項目</h2><div id="items" class="stack"></div></div><div class="card"><h2>主要聯絡人</h2><div class="grid2"><div class="field"><label>姓名 *</label><input id="name" required></div><div class="field"><label>手機</label><input id="phone" inputmode="tel"></div><div class="field"><label>Email</label><input id="email" type="email"></div></div>'+contactFields.map(f=>fieldHtml(f,'contact')).join('')+'</div><div id="attendees"></div><div class="card"><div class="row between mobile"><div><div class="muted">總人數</div><div id="count" class="total">0</div></div><div><div class="muted">總金額</div><div id="amount" class="total">$0</div></div></div><p id="modeHint" class="notice"></p><button class="btn primary" style="width:100%" type="submit">確認送出報名</button></div></form>';renderItems();document.getElementById('session')?.addEventListener('change',()=>{for(const k of Object.keys(quantities))quantities[k]=0;renderItems();recalc()});document.getElementById('regForm').onsubmit=submit;recalc();}
  function renderItems(){const sid=document.getElementById('session')?.value||'';const items=data.items.filter(x=>!x.session_id||x.session_id===sid);document.getElementById('items').innerHTML=items.map(x=>'<div class="item"><div class="row between mobile"><div><h3>'+esc(x.name)+'</h3><div class="muted">'+esc(x.description||'')+(x.capacity!=null?'｜名額 '+x.capacity:'')+'</div><div class="price">'+money(x.unit_price)+' / '+esc(x.unit_label||'人')+'</div></div><div class="qty"><button type="button" data-id="'+esc(x.id)+'" data-d="-1">−</button><input readonly value="'+Number(quantities[x.id]||0)+'"><button type="button" data-id="'+esc(x.id)+'" data-d="1">＋</button></div></div></div>').join('')||'<div class="notice">此梯次目前沒有可報名項目</div>';document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{const x=data.items.find(i=>i.id===b.dataset.id);let q=Number(quantities[x.id]||0)+Number(b.dataset.d);q=Math.max(Number(x.min_quantity||0),q);if(x.max_quantity!=null)q=Math.min(Number(x.max_quantity),q);quantities[x.id]=q;renderItems();recalc()});}
  function collectAttendees(){const out=[];document.querySelectorAll('[data-att-prefix]').forEach(h=>{const p=h.dataset.attPrefix;out.push({itemId:h.dataset.attItem,attendeeIndex:Number(h.dataset.attIndex),name:document.querySelector('[data-att-name="'+CSS.escape(p)+'"]')?.value||'',phone:document.querySelector('[data-att-phone="'+CSS.escape(p)+'"]')?.value||'',email:document.querySelector('[data-att-email="'+CSS.escape(p)+'"]')?.value||'',customData:collectCustom(p)})});return out;}
  async function submit(ev){ev.preventDefault();const btn=ev.submitter||ev.target.querySelector('button[type=submit]');btn.disabled=true;btn.textContent='送出中...';try{const body={sessionId:document.getElementById('session')?.value||undefined,identity:{type:'guest',provider:'guest'},contact:{name:document.getElementById('name').value.trim(),phone:document.getElementById('phone').value.trim(),email:document.getElementById('email').value.trim()},items:selectedItems(),customData:collectCustom('contact'),attendees:collectAttendees()};const r=await fetch('/api/v1/events/'+encodeURIComponent(EVENT_ID)+'/registrations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!d.success)throw new Error(d.error||'報名失敗');location.href='/registration/'+encodeURIComponent(d.accessToken)}catch(e){alert(e.message||'報名失敗');btn.disabled=false;btn.textContent='確認送出報名'}}
  fetch('/api/v1/events/'+encodeURIComponent(EVENT_ID)).then(r=>r.json()).then(d=>{if(!d.success)throw new Error(d.error);data=d;render()}).catch(e=>document.getElementById('app').innerHTML='<div class="card notice">'+esc(e.message||'活動載入失敗')+'</div>');`));
}

export async function validateRequiredFields(env: Env, eventId: string, request: Request): Promise<Response | null> {
  const body = await request.clone().json<any>();
  const fields = await env.CLASS_DB.prepare('SELECT * FROM event_form_fields WHERE event_id=? AND is_required=1 ORDER BY scope,sort_order').bind(eventId).all<Record<string,any>>();
  for (const f of fields.results) {
    if (f.scope === 'contact') {
      const v = body?.customData?.[f.field_key];
      if (v == null || v === '' || (Array.isArray(v)&&!v.length)) return new Response(JSON.stringify({success:false,error:`請填寫：${f.label}`}),{status:400,headers:{'content-type':'application/json; charset=utf-8'}});
    } else {
      const arr = Array.isArray(body?.attendees) ? body.attendees : [];
      for (let i=0;i<arr.length;i++) {
        const v = arr[i]?.customData?.[f.field_key];
        if (v == null || v === '' || (Array.isArray(v)&&!v.length)) return new Response(JSON.stringify({success:false,error:`第 ${i+1} 位參加者請填寫：${f.label}`}),{status:400,headers:{'content-type':'application/json; charset=utf-8'}});
      }
    }
  }
  return null;
}
