function page(title: string, body: string, script = '') {
  return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>
  *{box-sizing:border-box}body{margin:0;font-family:system-ui,-apple-system,"Noto Sans TC",sans-serif;background:#f6f7f9;color:#1f2937}.wrap{max-width:860px;margin:0 auto;padding:18px}.card{background:#fff;border-radius:18px;padding:20px;box-shadow:0 8px 28px rgba(0,0,0,.06);margin-bottom:16px}.hero{padding:0;overflow:hidden}.hero img{width:100%;max-height:380px;object-fit:cover;display:block}.hero .inner{padding:20px}h1,h2,h3{margin:0 0 12px}.muted{color:#6b7280}.row{display:flex;gap:12px;align-items:center}.between{justify-content:space-between}.stack{display:grid;gap:12px}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}.field label{display:block;font-weight:700;margin-bottom:6px}.field input,.field select,.field textarea{width:100%;padding:12px;border:1px solid #d1d5db;border-radius:12px;font-size:16px;background:#fff}.btn{border:0;border-radius:12px;padding:12px 16px;font-size:16px;font-weight:800;cursor:pointer}.primary{background:#111827;color:#fff}.secondary{background:#eef2f7;color:#111827}.danger{background:#dc2626;color:#fff}.qty{display:flex;align-items:center;gap:10px}.qty button{width:38px;height:38px;border:0;border-radius:10px;font-size:20px}.qty input{width:58px;text-align:center;padding:9px;border:1px solid #d1d5db;border-radius:10px}.price{font-size:19px;font-weight:800}.total{font-size:26px;font-weight:900}.pill{display:inline-block;padding:5px 10px;border-radius:999px;background:#eef2ff;color:#3730a3;font-size:13px;font-weight:700}.item{padding:14px;border:1px solid #e5e7eb;border-radius:14px}.notice{padding:12px 14px;border-radius:12px;background:#fff7ed;color:#9a3412}.ok{background:#ecfdf5;color:#166534}.nav{display:flex;gap:8px;margin-bottom:14px}.nav a{text-decoration:none;color:#111827;background:white;padding:9px 12px;border-radius:10px;font-weight:700}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:10px;border-bottom:1px solid #e5e7eb;text-align:left}.hidden{display:none}@media(max-width:640px){.grid2{grid-template-columns:1fr}.row.mobile-stack{display:grid}.wrap{padding:10px}.card{border-radius:14px;padding:16px}}
  </style></head><body>${body}<script>${script}</script></body></html>`;
}

export function renderHome(appName: string) {
  return page(appName, `<div class="wrap"><div class="card"><span class="pill">Registration Engine</span><h1>${appName}</h1><p>萬用活動報名系統</p><div class="row"><a class="btn primary" href="/events">活動列表</a><a class="btn secondary" href="/admin">活動管理</a></div></div></div>`);
}

export function renderEventList() {
  return page('活動列表', `<div class="wrap"><div class="nav"><a href="/">首頁</a><a href="/admin">管理</a></div><div class="card"><h1>目前活動</h1><div id="list" class="stack"><p class="muted">載入中...</p></div></div></div>`, `
  const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  fetch('/api/v1/events').then(r=>r.json()).then(d=>{const el=document.getElementById('list');if(!d.events?.length){el.innerHTML='<p class="muted">目前沒有開放中的活動</p>';return;}el.innerHTML=d.events.map(e=>'<a class="item" style="text-decoration:none;color:inherit" href="/event/'+encodeURIComponent(e.id)+'"><div class="between row"><div><h3>'+esc(e.title)+'</h3><div class="muted">'+esc(e.starts_at||'時間待定')+' · '+esc(e.location_name||'地點待定')+'</div></div><span class="pill">報名</span></div></a>').join('')}).catch(()=>document.getElementById('list').innerHTML='<div class="notice">活動載入失敗</div>');`);
}

export function renderEventPage(eventId: string) {
  const safeId = JSON.stringify(eventId);
  return page('活動報名', `<div class="wrap"><div class="nav"><a href="/events">返回活動</a></div><div id="app"><div class="card">載入中...</div></div></div>`, `
  const EVENT_ID=${safeId}; let data=null;
  const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  const money=n=>new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(Number(n||0));
  function render(){const e=data.event,s=data.sessions||[],items=data.items||[];document.title=e.title;document.getElementById('app').innerHTML=
    '<div class="card hero">'+(e.banner_url?'<img src="'+esc(e.banner_url)+'" alt="">':'')+'<div class="inner"><h1>'+esc(e.title)+'</h1><p class="muted">'+esc(e.starts_at||'')+(e.location_name?' · '+esc(e.location_name):'')+'</p><p>'+esc(e.description||'').replace(/\n/g,'<br>')+'</p></div></div>'+
    '<form id="regForm">'+(s.length?'<div class="card"><h2>選擇梯次</h2><div class="field"><select id="session" required><option value="">請選擇</option>'+s.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.name)+(x.starts_at?'｜'+esc(x.starts_at):'')+'</option>').join('')+'</select></div></div>':'')+
    '<div class="card"><h2>報名項目</h2><div class="stack">'+items.map(x=>'<div class="item" data-session="'+esc(x.session_id||'')+'"><div class="row between mobile-stack"><div><h3>'+esc(x.name)+'</h3><div class="muted">'+esc(x.description||'')+'</div><div class="price">'+money(x.unit_price)+' / '+esc(x.unit_label||'人')+'</div></div><div class="qty"><button type="button" data-delta="-1" data-id="'+esc(x.id)+'">−</button><input readonly id="q_'+esc(x.id)+'" value="0"><button type="button" data-delta="1" data-id="'+esc(x.id)+'">＋</button></div></div></div>').join('')+'</div></div>'+
    '<div class="card"><h2>聯絡人資料</h2><div class="grid2"><div class="field"><label>姓名 *</label><input id="name" required></div><div class="field"><label>手機</label><input id="phone" inputmode="tel"></div><div class="field"><label>Email</label><input id="email" type="email"></div><div class="field"><label>報名方式</label><select id="identity"><option value="guest">自行填寫</option>'+(e.identity_mode!=='guest_only'?'<option value="member">會員 / 外部登入</option>':'')+'</select></div></div></div>'+
    '<div class="card"><div class="row between mobile-stack"><div><div class="muted">報名總人數</div><div id="count" class="total">0</div></div><div><div class="muted">總金額</div><div id="amount" class="total">$0</div></div></div><p id="modeHint" class="notice"></p><button class="btn primary" style="width:100%" type="submit">確認送出報名</button></div></form>';
    bind(); recalc();
  }
  function visibleItems(){const sid=document.getElementById('session')?.value||'';return data.items.filter(x=>!x.session_id||x.session_id===sid)}
  function recalc(){let c=0,a=0;for(const x of data.items){const q=Number(document.getElementById('q_'+x.id)?.value||0);c+=q;a+=q*Number(x.unit_price)}document.getElementById('count').textContent=c;document.getElementById('amount').textContent=money(a);const e=data.event;let t='免費活動：送出後直接完成報名';if(a>0&&e.registration_success_mode==='register_then_pay')t='先完成報名，之後再付款';if(a>0&&e.registration_success_mode==='pay_then_confirm')t='付款完成後才算正式報名成功';document.getElementById('modeHint').textContent=t;}
  function bind(){document.querySelectorAll('[data-delta]').forEach(b=>b.onclick=()=>{const x=data.items.find(i=>i.id===b.dataset.id),inp=document.getElementById('q_'+x.id);let q=Number(inp.value)+Number(b.dataset.delta);q=Math.max(Number(x.min_quantity||0),q);if(x.max_quantity!=null)q=Math.min(Number(x.max_quantity),q);inp.value=q;recalc()});document.getElementById('session')?.addEventListener('change',e=>{document.querySelectorAll('.item').forEach(n=>{const sid=n.dataset.session;n.classList.toggle('hidden',!!sid&&sid!==e.target.value)});for(const x of data.items){if(x.session_id&&x.session_id!==e.target.value)document.getElementById('q_'+x.id).value=0}recalc()});document.getElementById('regForm').onsubmit=submit;}
  async function submit(ev){ev.preventDefault();const btn=ev.target.querySelector('button[type=submit]');btn.disabled=true;btn.textContent='送出中...';try{const items=data.items.map(x=>({itemId:x.id,quantity:Number(document.getElementById('q_'+x.id).value)})).filter(x=>x.quantity>0);const identityType=document.getElementById('identity').value;if(data.event.identity_mode==='login_required'&&identityType!=='member')throw new Error('此活動必須使用登入身份報名');const body={sessionId:document.getElementById('session')?.value||undefined,contact:{name:document.getElementById('name').value,phone:document.getElementById('phone').value,email:document.getElementById('email').value},identity:{type:identityType,provider:identityType==='member'?'external':'guest'},items};const r=await fetch('/api/v1/events/'+encodeURIComponent(EVENT_ID)+'/registrations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!d.success)throw new Error(d.error||'報名失敗');location.href='/registration/'+encodeURIComponent(d.accessToken)}catch(err){alert(err.message||'報名失敗');btn.disabled=false;btn.textContent='確認送出報名'}}
  fetch('/api/v1/events/'+encodeURIComponent(EVENT_ID)).then(r=>r.json()).then(d=>{if(!d.success)throw new Error(d.error);data=d;render()}).catch(e=>document.getElementById('app').innerHTML='<div class="card notice">'+esc(e.message||'活動載入失敗')+'</div>');`);
}

export function renderRegistrationPage(token: string) {
  const safe = JSON.stringify(token);
  return page('我的報名', `<div class="wrap"><div class="nav"><a href="/events">活動列表</a></div><div id="app" class="card">載入中...</div></div>`, `
  const TOKEN=${safe};const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));const money=n=>new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(Number(n||0));
  function status(s){return ({pending_payment:'待付款',confirmed:'報名成功',cancelled:'已取消',expired:'已逾期',checked_in:'已報到',waitlist:'候補'}[s]||s)}
  async function load(){const r=await fetch('/api/v1/registrations/token/'+encodeURIComponent(TOKEN));const d=await r.json();if(!d.success){document.getElementById('app').innerHTML='<div class="notice">找不到報名資料</div>';return}const x=d.registration;document.getElementById('app').innerHTML='<span class="pill">'+status(x.registration_status)+'</span><h1>'+esc(x.event_title)+'</h1><p>報名編號：<b>'+esc(x.registration_no)+'</b></p><p>'+esc(x.contact_name)+' · '+esc(x.contact_phone||'')+'</p><div class="stack">'+d.items.map(i=>'<div class="item row between"><span>'+esc(i.item_name_snapshot)+' × '+i.quantity+'</span><b>'+money(i.subtotal)+'</b></div>').join('')+'</div><hr><div class="row between"><span>總金額</span><span class="total">'+money(x.total_amount)+'</span></div><p class="muted">付款狀態：'+esc(x.payment_status)+'</p>'+(!['cancelled','checked_in'].includes(x.registration_status)?'<button id="cancel" class="btn danger">取消報名</button>':'');document.getElementById('cancel')?.addEventListener('click',async()=>{if(!confirm('確定取消這筆報名？'))return;const rr=await fetch('/api/v1/registrations/token/'+encodeURIComponent(TOKEN)+'/cancel',{method:'POST'});const dd=await rr.json();if(!dd.success){alert(dd.error||'取消失敗');return}load()})}load();`);
}

export function renderAdminPage() {
  return page('活動管理', `<div class="wrap"><div class="nav"><a href="/">首頁</a><a href="/events">前台活動</a></div><div class="card"><div class="row between"><div><h1>活動管理</h1><p class="muted">建立活動、梯次、項目與付款成立方式</p></div><button id="newBtn" class="btn primary">＋ 建立活動</button></div></div><div id="form" class="card hidden"></div><div id="list" class="card"><h2>活動</h2><div id="rows" class="stack">載入中...</div></div></div>`, `
  const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));const f=document.getElementById('form');
  function openForm(){f.classList.remove('hidden');f.innerHTML='<h2>建立活動</h2><div class="stack"><div class="field"><label>活動名稱 *</label><input id="title"></div><div class="grid2"><div class="field"><label>開始時間</label><input id="starts" type="datetime-local"></div><div class="field"><label>地點</label><input id="location"></div></div><div class="field"><label>活動說明</label><textarea id="desc" rows="4"></textarea></div><div class="grid2"><div class="field"><label>報名身份模式</label><select id="identity"><option value="hybrid">登入或自行填寫皆可</option><option value="login_required">必須登入</option><option value="guest_only">只接受自行填寫</option></select></div><div class="field"><label>報名成立方式</label><select id="success"><option value="free">免費／送出即成功</option><option value="register_then_pay">先報名成功，後付款</option><option value="pay_then_confirm">付款完成才成功</option></select></div></div><div class="grid2"><div class="field"><label>活動總名額</label><input id="capacity" type="number" min="1"></div><div class="field"><label>付款保留分鐘</label><input id="hold" type="number" value="15" min="1"></div></div><h3>報名項目</h3><div id="items" class="stack"></div><button id="addItem" class="btn secondary" type="button">＋ 新增項目</button><button id="save" class="btn primary" type="button">建立並發布</button></div>';document.getElementById('addItem').onclick=addItem;document.getElementById('save').onclick=save;addItem()}
  function addItem(){const n=document.createElement('div');n.className='item grid2';n.innerHTML='<div class="field"><label>項目名稱</label><input class="iname" placeholder="會員 / 一般 / 兒童"></div><div class="field"><label>單價</label><input class="iprice" type="number" min="0" value="0"></div><div class="field"><label>每筆最多人數</label><input class="imax" type="number" min="1" value="10"></div><div class="field"><label>項目總名額</label><input class="icap" type="number" min="1"></div>';document.getElementById('items').appendChild(n)}
  async function save(){const items=[...document.querySelectorAll('#items .item')].map(n=>({name:n.querySelector('.iname').value,unitPrice:Number(n.querySelector('.iprice').value||0),maxQuantity:Number(n.querySelector('.imax').value||10),capacity:n.querySelector('.icap').value?Number(n.querySelector('.icap').value):null})).filter(x=>x.name.trim());if(!document.getElementById('title').value.trim())return alert('請填活動名稱');if(!items.length)return alert('至少建立一個報名項目');const body={title:document.getElementById('title').value,description:document.getElementById('desc').value,locationName:document.getElementById('location').value,startsAt:document.getElementById('starts').value||null,capacity:document.getElementById('capacity').value?Number(document.getElementById('capacity').value):null,identityMode:document.getElementById('identity').value,registrationSuccessMode:document.getElementById('success').value,paymentHoldMinutes:Number(document.getElementById('hold').value||15),items};const r=await fetch('/api/v1/admin/events',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!d.success)return alert(d.error||'建立失敗');f.classList.add('hidden');load()}
  async function load(){const r=await fetch('/api/v1/admin/events');const d=await r.json();const rows=document.getElementById('rows');if(!d.events?.length){rows.innerHTML='<p class="muted">尚未建立活動</p>';return}rows.innerHTML=d.events.map(e=>'<div class="item"><div class="row between mobile-stack"><div><h3>'+esc(e.title)+'</h3><div class="muted">'+esc(e.starts_at||'時間待定')+' · '+esc(e.location_name||'地點待定')+'</div></div><div class="row"><span class="pill">'+esc(e.status)+'</span><a class="btn secondary" href="/event/'+encodeURIComponent(e.id)+'">預覽</a></div></div></div>').join('')}document.getElementById('newBtn').onclick=openForm;load();`);
}
